name: 'NDepend'
description: 'NDepend parser'
inputs:
  license:  
    description: 'NDepend license file'
    required: true
    default: ''
  baseline:  
    description: 'NDepend baseline'
    required: false
    default: ''
  solution:  
    description: '.sln file'
    required: false
    default: ''
  stopIfQGFailed:  
    description: 'Stop if at least one quality gate failed'
    required: false
    default: false
  customconfig:  
    description: 'Custom NDepend configuration file'
    required: false
    default: ''
  coveragefolder: 
    description: 'Coverage Directory'
    required: false
    default: ''

runs:
  using: 'node12'
  main: 'dist/index.js'
